services:
  postgres:
    image: postgres:latest
    container_name: avitocoinshop_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "6432:5432"
    networks:
      - avito-coin-shop-network
   
    volumes:
      - avitocoinshop_db_data_latest:/var/lib/postgresql/data
  
  app:
    container_name: avitocoinshop_app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - avito-coin-shop-network
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres;


networks:
  avito-coin-shop-network:
    driver: bridge
volumes:
  avitocoinshop_db_data_latest:
