using FluentMigrator;

namespace AvitoCoinShop.Infrastructure.Persistence.Migrations;

[Migration(20250215_4)]
public class CreateTransferHistoryTable : Migration
{
    public override void Up()
    {
        Execute.Sql(@"
            CREATE TABLE transfer_history (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                sender_id BIGINT NOT NULL,
                receiver_id BIGINT NOT NULL,
                amount INT NOT NULL CHECK (amount > 0),
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
                CONSTRAINT fk_sender FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
                CONSTRAINT fk_receiver FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE
            );
        ");
    }

    public override void Down()
    {
        Execute.Sql("DROP TABLE transfer_history;");
    }
}