using FluentMigrator;

namespace AvitoCoinShop.Infrastructure.Persistence.Migrations;

[Migration(20250215_5)]
public class CreatePurchaseHistoryTable : Migration
{
    public override void Up()
    {
        Execute.Sql(@"
            CREATE TABLE purchase_history (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                user_id BIGINT NOT NULL,
                item_id BIGINT NOT NULL,
                price INT NOT NULL CHECK (price > 0),
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
                CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                CONSTRAINT fk_item FOREIGN KEY (item_id) REFERENCES merch_items(id) ON DELETE CASCADE
            );
        ");
    }

    public override void Down()
    {
        Execute.Sql("DROP TABLE purchase_history;");
    }
}