using FluentMigrator;

namespace AvitoCoinShop.Infrastructure.Persistence.Migrations;

[Migration(20250215_1)]
public class CreateMerchTable : Migration
{
    public override void Up()
    {
        Execute.Sql(@"
            CREATE TABLE merch_items (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                name VARCHAR(255) NOT NULL UNIQUE,
                price INT NOT NULL CHECK (price > 0)
            );
        ");
        
        Execute.Sql(@"
            INSERT INTO merch_items (name, price) VALUES
            ('t-shirt', 80),
            ('cup', 20),
            ('book', 50),
            ('pen', 10),
            ('powerbank', 200),
            ('hoody', 300),
            ('umbrella', 200),
            ('socks', 10),
            ('wallet', 50),
            ('pink-hoody', 500);
        ");
    }

    public override void Down()
    {
        Execute.Sql("DROP TABLE merch_items;");
    }
}