using FluentMigrator;

namespace AvitoCoinShop.Infrastructure.Persistence.Migrations;

[Migration(20250215_2)]
public class CreateUsersTable : Migration
{
    public override void Up()
    {
        Execute.Sql(@"
            CREATE TABLE users (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                name VARCHAR(255) NOT NULL,
                balance INT NOT NULL DEFAULT 1000 CHECK (balance >= 0),
                password_hash VARCHAR(255) NOT NULL,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
            );
        ");
    }

    public override void Down()
    {
        Execute.Sql("DROP TABLE users;");
    }
}